<template>
  <div id="app" class=" shadow-lg w-full py-12 px-4 sm:px-6 lg:px-8">
    <h2 class="text-2xl font-bold text-center mb-8 text-primary">Posts</h2>
    <BlogTimeline :posts="posts" />
  </div>
</template>

<script setup>
import BlogTimeline from './PostTimeline.vue'

const posts = [
  {
    "time": "2024-09-15",
    "title": "Getting Started with Vue.js 3 Composition API",
    "description": "Learn how to use the new Composition API in Vue.js 3 to build more maintainable and scalable applications.",
    "author": "PoPi",
    "category": "Technology",
    "content": "<p><strong>Vue.js 3</strong> introduced the <em>Composition API</em>, a new way to organize and reuse logic in Vue components. Unlike the <strong>Options API</strong>, which organizes code by options like data, methods, and computed properties, the Composition API allows you to organize code by logical concerns.</p><p>The Composition API is centered around the <code>setup()</code> function, which is executed before the component is created. This function can return an object containing properties and methods that will be exposed to the template.</p><p>Let's look at a simple example:</p><pre><code>import { ref, computed } from 'vue'\n\nexport default {\n  setup() {\n    // Reactive state\n    const count = ref(0)\n    \n    // Computed property\n    const doubleCount = computed(() => count.value * 2)\n    \n    // Method\n    function increment() {\n      count.value++\n    }\n    \n    // Expose to template\n    return {\n      count,\n      doubleCount,\n      increment\n    }\n  }\n}</code></pre><p>The Composition API makes it easier to extract and reuse logic across components. You can create composable functions that encapsulate related logic and use them in multiple components.</p><p>For example, you could create a <strong>useCounter</strong> composable:</p><pre><code>import { ref, computed } from 'vue'\n\nexport function useCounter() {\n  const count = ref(0)\n  const doubleCount = computed(() => count.value * 2)\n  \n  function increment() {\n    count.value++\n  }\n  \n  return {\n    count,\n    doubleCount,\n    increment\n  }\n}</code></pre><p>And then use it in a component:</p><pre><code>import { useCounter } from './composables/counter'\n\nexport default {\n  setup() {\n    const { count, doubleCount, increment } = useCounter()\n    \n    return {\n      count,\n      doubleCount,\n      increment\n    }\n  }\n}</code></pre><p>The Composition API is a powerful tool for building complex applications with Vue.js. It allows for better code organization, improved type inference, and more efficient reuse of logic.</p>"
  },
  {
    "time": "2024-08-22",
    "title": "Responsive Design Principles for Modern Web Applications",
    "description": "Explore key principles and techniques for creating responsive web designs that work well on all devices.",
    "author": "PoPi",
    "category": "Design",
    "content": "<p><strong>Responsive web design</strong> is an approach to web design that makes web pages render well on a variety of devices and window or screen sizes. It's essential for providing a good user experience regardless of whether a user is accessing your site from a desktop computer, tablet, or smartphone.</p><p>Here are some key principles for responsive design:</p><ol><li><strong>Fluid Grids</strong>: Use relative units like percentages instead of fixed units like pixels for layout elements. This allows the layout to scale based on the viewport size.</li><li><strong>Flexible Images</strong>: Images should also scale with the layout. You can achieve this by setting <code>max-width: 100%</code> on images, which ensures they never exceed the width of their container.</li><li><strong>Media Queries</strong>: Use CSS media queries to apply different styles based on the characteristics of the device, such as its width, height, or orientation.</li><li><strong>Mobile-First Approach</strong>: Start designing for the smallest screen size first, then progressively enhance the design for larger screens. This approach forces you to focus on the essential content and functionality.</li><li><strong>Breakpoints</strong>: Establish breakpoints where your design will change to accommodate different screen sizes. Common breakpoints are around 576px, 768px, 992px, and 1200px, but you should base your breakpoints on your content, not on specific devices.</li></ol><p>Here's a simple example of a responsive layout using CSS Grid:</p><pre><code>.container {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\n  gap: 1rem;\n}</code></pre><p>This creates a grid where each column is at least 300px wide, and as many columns as can fit will be created. As the viewport width changes, the number of columns will adjust automatically.</p><p>For more complex layouts, you might use a combination of CSS Grid and Flexbox, along with media queries to adjust the layout at different breakpoints.</p><p>Remember, the goal of responsive design is to provide an optimal viewing experience across a wide range of devices. By following these principles, you can create web applications that look and work great regardless of the device they're viewed on.</p>"
  },
  {
    "time": "2024-07-10",
    "title": "Optimizing Database Performance in Laravel Applications",
    "description": "Learn techniques to improve database performance in Laravel applications, from query optimization to caching strategies.",
    "author": "PoPi",
    "category": "Tutorial",
    "content": "<p><strong>Database performance</strong> is crucial for the overall performance of your Laravel application. In this post, we'll explore various techniques to optimize database performance in Laravel applications.</p><ol><li><strong>Use Eager Loading to Avoid N+1 Query Problem</strong></li><p>The N+1 query problem occurs when you retrieve a collection of models and then access a relationship for each model, resulting in an additional query for each model. Laravel's eager loading can solve this problem:</p><pre><code>// Instead of this (N+1 problem)\n$books = Book::all();\nforeach ($books as $book) {\n  echo $book->author->name;\n}\n\n// Do this (eager loading)\n$books = Book::with('author')->get();\nforeach ($books as $book) {\n  echo $book->author->name;\n}</code></pre><li><strong>Use Query Caching</strong></li><p>Larael provides a simple way to cache query results:</p><pre><code>$users = Cache::remember('users', 60, function () {\n  return User::all();\n});</code></pre><li><strong>Use Database Indexes</strong></li><p>Indexes can significantly improve the performance of your queries, especially for large tables:</p><pre><code>// Add an index to a column in a migration\nSchema::table('users', function (Blueprint $table) {\n  $table->index('email');\n});</code></pre><li><strong>Chunk Large Datasets</strong></li><p>When working with large datasets, use the chunk method to process records in smaller batches:</p><pre><code>User::chunk(100, function ($users) {\n  foreach ($users as $user) {\n    // Process each user\n  }\n});</code></pre><li><strong>Use Query Builders Instead of Eloquent When Appropriate</strong></li><p>Eloquent is convenient, but for complex queries or when you need maximum performance, consider using the query builder:</p><pre><code>// Eloquent (creates and hydrates model instances)\n$users = User::where('active', 1)->get();\n\n// Query Builder (returns plain arrays, faster)\n$users = DB::table('users')->where('active', 1)->get();</code></pre><li><strong>Optimize Your Database Schema</strong></li><p>Ensure your database schema is properly designed:</p><ul><li>Use appropriate data types</li><li>Normalize your database to reduce redundancy</li><li>Use foreign keys for data integrity</li></ul><li><strong>Use Laravel's Database Transactions</strong></li><p>Wrap related operations in transactions to ensure data integrity and improve performance:</p><pre><code>DB::transaction(function () {\n  // Perform multiple database operations\n});</code></pre></ol><p>By implementing these techniques, you can significantly improve the database performance of your Laravel applications, resulting in faster response times and a better user experience.</p>"
  },
  {
    "time": "2024-06-05",
    "title": "Building a Personal Brand as a Developer",
    "description": "Discover strategies for building your personal brand as a developer to stand out in the competitive tech industry.",
    "author": "PoPi",
    "category": "Business",
    "content": "<p>In today's competitive tech industry, <strong>building a personal brand</strong> as a developer is more important than ever. Your personal brand is how you present yourself professionally and how others perceive you in the industry. It can help you stand out from the crowd, attract better job opportunities, and establish yourself as an authority in your field.</p><p>Here are some strategies for building a strong personal brand as a developer:</p><ol><li><strong>Find Your Niche</strong>: While it's good to have broad knowledge, specializing in a specific area can help you stand out. Choose a technology, framework, or problem domain that you're passionate about and become an expert in it.</li><li><strong>Create and Share Content</strong>: One of the most effective ways to build your brand is by creating and sharing valuable content. This could be through:</li><ul><li>Writing blog posts or articles</li><li>Creating tutorial videos</li><li>Contributing to open-source projects</li><li>Speaking at conferences or meetups</li><li>Answering questions on platforms like Stack Overflow</li></ul><li><strong>Build an Online Presence</strong>: Establish a strong online presence through:</li><ul><li>A personal website or portfolio showcasing your projects and skills</li><li>Active profiles on professional networks like LinkedIn and GitHub</li><li>Engagement on social media platforms relevant to your field</li></ul><li><strong>Network Actively</strong>: Networking is crucial for brand building:</li><ul><li>Attend industry events, conferences, and meetups</li><li>Join online communities and forums</li><li>Participate in hackathons and coding challenges</li><li>Connect with other professionals in your field</li></ul><li><strong>Contribute to Open Source</strong>: Contributing to open-source projects demonstrates your skills and commitment to the community. It also helps you build connections with other developers.</li><li><strong>Develop Soft Skills</strong>: Technical skills are important, but soft skills like communication, teamwork, and problem-solving are equally valuable for your brand:</li><ul><li>Practice explaining complex technical concepts in simple terms</li><li>Learn to give and receive feedback effectively</li><li>Develop your writing and presentation skills</li></ul><li><strong>Be Consistent and Authentic</strong>: Consistency in your messaging and authenticity in your interactions are key to building trust:</li><ul><li>Be genuine in your communications</li><li>Deliver on your promises</li><li>Admit when you don't know something and show your willingness to learn</li></ul></ol><p>Building a personal brand takes time and effort, but the benefits are well worth it. By establishing yourself as a knowledgeable and trustworthy professional, you'll create more opportunities for career growth and professional satisfaction.</p>"
  },
  {
    "time": "2024-05-18",
    "title": "Mindfulness Practices for Developers",
    "description": "Explore mindfulness techniques that can help developers reduce stress, improve focus, and enhance productivity.",
    "author": "PoPi",
    "category": "Lifestyle",
    "content": "<p><strong>Mindfulness</strong> practices can help developers reduce stress, improve focus, and enhance overall well-being. In this post, we explore techniques specifically for developers to help them manage their stress and boost productivity.</p><h3>What is Mindfulness?</h3><p>Mindfulness is the practice of paying attention to the present moment with openness, curiosity, and without judgment. It involves being aware of your thoughts, feelings, bodily sensations, and environment.</p><h3>Benefits of Mindfulness for Developers</h3><ul><li>Improved focus and concentration</li><li>Enhanced problem-solving abilities</li><li>Reduced stress and anxiety</li><li>Better error detection</li><li>Increased creativity</li><li>Improved work relationships</li><li>Better work-life balance</li></ul><h3>Mindfulness Practices for Developers</h3><ol><li><strong>Mindful Breathing</strong>: Take short breaks throughout your day to focus on your breath.</li><li><strong>Pomodoro Technique with Mindfulness</strong>: Combine Pomodoro with mindfulness for increased focus.</li><li><strong>Mindful Coding</strong>: Bring awareness to the process of coding itself.</li><li><strong>Digital Detox</strong>: Disconnect from technology at certain times.</li><li><strong>Mindful Walking</strong>: Take short walking breaks to reset your mind.</li><li><strong>Gratitude Practice</strong>: Reflect on three things you're grateful for at the end of the day.</li></ol><p>By incorporating mindfulness into your daily routine, you can improve your focus, reduce stress, and enhance productivity. It’s a practice that grows with time, so be patient with yourself.</p>"
  },
]
</script>